In [15]:
# Functions

# A function is a block of code which only runs when it is called.

# A function can return data as a result.

# A function helps avoiding code repetition.

# Creating a Function In Python, a function is defined using the def keyword,
#followed by a function name and parentheses:
     #function_name
def my_function():
  print("Hello from a function")
  print("I am Learning Functions in Python")
  print(5+9)


my_function() #calling a function
print("I am outside the function.")

Hello from a function
I am Learning Functions in Python
14
I am outside the function.


In [17]:
def my_function():
  print("Hello from a function we will print it three times.")  #defining a function
my_function() #calling a function multiple times
my_function()
# my_function()
# my_function()

Hello from a function we will print it three times.
Hello from a function we will print it three times.


In [ ]:
# # Function Names Function names follow the same rules as variable names in Python:

# # A function name must start with a letter or underscore A function name can only contain letters, numbers, and underscores Function names are case-sensitive (myFunction and myfunction are different)

# # It's good practice to use descriptive names that explain what the function does.

# # calculate_sum() _private_function() myFunction2()

# Why Use Functions?
# Imagine you need to convert temperatures from
# Fahrenheit to Celsius several times in your program. Without functions,
# you would have to write the same calculation code repeatedly

temp1 = 77
celsius1 = (temp1 - 32) * 5 / 9
print(celsius1)

temp2 = 95
celsius2 = (temp2 - 32) * 5 / 9
print(celsius2)

temp3 = 50
celsius3 = (temp3 - 32) * 5 / 9
print(celsius3)

25.0
35.0
10.0


In [ ]:
def fahrenheit_to_celsius(fahrenheit):
  return (fahrenheit - 32) * 5 / 9

print(fahrenheit_to_celsius(77))
print(fahrenheit_to_celsius(95))
print(fahrenheit_to_celsius(50))

25.0
35.0
10.0


In [ ]:
# Return Values Functions can send data back to the code that called them using the return statement.

# When a function reaches a return statement, it stops executing and sends the result back:

def get_greeting():
  return "Hello from a function"

message = get_greeting()
print(message)

Hello from a function


In [23]:
def get_greeting():
  return "hi"

print(get_greeting()) #directly

hi


In [ ]:
# If a function doesn't have a return statement, it returns None by default.

# write a function which prints your name.
def print_my_name():
  print("My name is Medhasree.")
print_my_name()

My name is Medhasree.


In [ ]:
# write a function which prints your sirname. (Use return)
def print_my_surname():
  return"My surname is Ghosh"
surname = print_my_surname()
print(surname)

My surname is Ghosh


In [ ]:
# Write a funtion which takes input of your name and display it.
def get_my_name():
  name = str(input("Enter your name:"))
  print(name)
get_my_name()


Enter your name: medha


medha


#Write a function which takes input of two numbers and return the addition of these two.


In [25]:
#let's define the function
def addition_num():
  num1 = int(input("Enter num1: "))
  num2 = int(input("Enter num2: "))
  result=num1+num2
  print("The addition result of two numbers are: " , result)
#call the function
addition_num()


Enter num1: 5
Enter num2: 3
The addition result of two numbers are, 8


Take input from users and calculate the area of a rectangle (lenth x width)

In [27]:
#let's define the function
def area_rect():
  length = float(input("Enter the length: "))
  width = float(input("Enter the width: "))
  area_rect_res=length*width
  print("The area of the given rectangle is: " , area_rect_res)
#call the function
area_rect()


Enter the length: 5.3
Enter the width: 2.3
The area of the given rectangle is:  12.19


Write a function that helps you figure out how much to tip at dinner.

Function Name: calculate_tip()

Task: If the bill is 100 and the tip is 15.

In [28]:
def calculate_tip():
  bill_amount = float(input("Enter the amount of your bill: "))
  tip = bill_amount * 0.15
  print("your tip is", tip)
calculate_tip()

Enter the amount of your bill: 14453.23
your tip is 2167.9845


Practice using if/else logic inside a function.

Function Name: is_even()

Requirement: The function should print True if the number is even and False if it’s odd.



In [30]:
def is_even():
  num = int(input("Enter a number: "))
  if num%2==0:
    print("This is an even number.")
  else:
    print("Odd number.")
is_even()

Enter a number: 7
Odd number.


Practice iterating through strings. Write a function that counts how many vowels (a, e, i, o, u) are in a word.

Function Name: count_vowels()

Example: Passing "banana" should return 3.

In [33]:
def count_vowels():
  string1 = str(input("Enter a string: "))
  count = 0
  for x in string1:
    if x == 'a':
      count = count+1
    elif x=='e':
      count = count+1
    elif x=='i':
      count = count+1
    elif x=='o':
      count = count+1
    elif x=='u':
      count = count+1
  print(count)
count_vowels()

Enter a string: fghjk
0


Write a function that takes a list of numbers and prints the total sum of all elements.

Function Name: sum_list()

Task: Use a for loop to iterate through the list and add each number to a "total" variable.

In [ ]:
# Write a function that checks if a password is "strong" based on its length.

# Function Name: is_strong()

# Requirement: Return True if the password is 8 characters or longer, and False otherwise.

# Hint: Use the len() function.

In [ ]:
# Function Name: guess_the_number()

# The Logic:

# Pick a "secret" number (like 7).

# Ask the user to input a guess.

# Compare the input to the secret number.

# Print "Too high!", "Too low!", or "You got it!" based on the result.

In [ ]:
# Write a function that takes a user's word and transforms it into a "shouting" version.

# Function Name: shout_echo()

# The Logic:

# Ask the user to enter a word or sentence.

# Convert that string to all UPPERCASE.

# Add three exclamation marks (!!!) to the end.

# Print the final result.

# Hint: In Python, you can use the .upper() method on any string.

In [ ]:
# Write a function that determines if a user is old enough to enter a venue.

# Function Name: check_entry()

# The Logic:

# Ask the user, "How old are you?"

# Convert the input to an integer.

# If the age is 21 or older, print "Welcome in! What can I get you?"

# If the age is between 18 and 20, print "You can come in, but you get a wristband (no drinks)."

# If the age is under 18, print "Sorry, you're too young to enter."

In [ ]:
# Create a function that lets a user build a small shopping list.

# Function Name: make_list()

# The Logic:

# Create an empty list called groceries.

# Use a for loop to ask the user 3 times: "What item do you want to add?"

# Use .append() to add each item to the list.

# After the loop, print "Your final shopping list is:" followed by the list.

In [ ]:
# Write a function that acts like a "Create Account" screen where the user has to confirm their password.

# Function Name: setup_password()

# The Logic:

# Ask the user to "Enter a new password."

# Ask the user to "Confirm your password."

# Check if the first entry matches the second entry.

# If they match: Print "Account created successfully!"

# If they don't match: Print "Error: Passwords do not match. Please try again."



In [1]:
# Arguments Information can be passed into functions as arguments.

# Arguments are specified after the function name, inside the parentheses.
#You can add as many arguments as you want, just separate them with a comma.

# The following example has a function with one argument (fname).
#When the function is called, we pass along a first name, which is used inside the function to print the full name:

def my_function(name):
  print(name + " this is a name")

my_function("Emil") #calling a function with argument
my_function("Tobias")
my_function("Linus")

Emil this is a name
Tobias this is a name
Linus this is a name


In [ ]:
# Parameters vs Arguments The terms parameter and argument can be used for the same thing:
#     information that are passed into a function.

# From a function's perspective:

# A parameter is the variable listed inside the parentheses in the function definition.

# An argument is the actual value that is sent to the function when it is called.

def my_function(name): # name is a parameter
  print("Hello", name)

my_function("Emil") # "Emil" is an argument

Hello Emil


In [2]:
# Number of Arguments By default, a function must be called with the correct number of arguments.

# If your function expects 2 arguments, you must call it with exactly 2 arguments.
def my_function(fname, lname):
  print(fname + " " + lname)

my_function("Emil", "devil") #by default it will follow the order

Emil devil


In [ ]:
# If you try to call the function with the wrong number of arguments, you will get an error:

# Example This function expects 2 arguments, but gets only 1:
def my_function(fname, lname):
  print(fname + " " + lname)
#one argument passed instead of two
my_function("Emil")

<class 'TypeError'>: my_function() missing 1 required positional argument: 'lname'

In [ ]:
# Default Parameter Values You can assign default values to parameters.
#     If the function is called without an argument, it uses the default value:

def my_function(name = "friend"): #default is "friend"
  print("Hello", name)

my_function("Emil")
my_function("Tobias")
my_function() #no arguments hence default
my_function("Linus")

Hello Emil
Hello Tobias
Hello friend
Hello Linus


In [ ]:
def my_function(country = "Norway"):
  print("I am from", country)

my_function("Sweden")
my_function("India")
my_function()
my_function("Brazil")

I am from Sweden
I am from India
I am from Norway
I am from Brazil


In [ ]:
# Keyword Arguments You can send arguments with the key = value syntax.

# Example

def my_function(animal, name):
  print("I have a", animal)
  print("My", animal + "'s name is", name)

my_function(animal = "dog", name = "Buddy")

I have a dog
My dog's name is Buddy


In [ ]:
# This way, with keyword arguments, the order of the arguments does not matter.

def my_function(animal, name):
  print("I have a", animal)
  print("My", animal + "'s name is", name)

my_function(name = "Buddy", animal = "dog")

I have a dog
My dog's name is Buddy


In [35]:
# Positional Arguments When you call a function with arguments without using keywords, they are called positional arguments.

# Positional arguments must be in the correct order:

def my_function(animal, name):
  print("I have a", animal)
  print("My", animal + "'s name is", name)

my_function("Dog", "buddy")

I have a Dog
My Dog's name is buddy


In [ ]:
# The order matters with positional arguments:

# Example Switching the order changes the result:
def my_function(animal, name):
  print("I have a", animal)
  print("My", animal + "'s name is", name)

my_function("Buddy", "dog")

I have a Buddy
My Buddy's name is dog


In [37]:
# Mixing Positional and Keyword Arguments You can mix positional and keyword arguments in a function call.

# However, positional arguments must come before keyword arguments:
def my_function(animal, name, age):
  print("I have a", age, "year old", animal, "named", name)

my_function("dog", name="buddy", age = 5)

I have a 5 year old dog named buddy


In [38]:
# Passing Different Data Types
# You can send any data type as an argument to a function (string, number, list, dictionary, etc.).

# The data type will be preserved inside the function:
def my_function(fruits):
  for fruit in fruits: #iterating through fruits
    print(fruit)

my_fruits = ["apple", "banana", "cherry"] #this is a list
my_function(my_fruits)
print(type(my_fruits))

apple
banana
cherry
<class 'list'>


In [6]:
def my_function(person):  #dictionary as an argument
  print("Name:", person["name"])
  print("Age:", person["age"])

my_person = {"name": "Emil", "age": 25}
my_function(my_person)
print(type(my_person))

Name: Emil
Age: 25
<class 'dict'>


In [ ]:
# Return Values Functions can return values using the return statement:
def my_function(x, y):
  return x + y

result = my_function(5, 3)
print(result)

8


In [40]:
# Returning Different Data Types Functions can return any data type,
# including lists, tuples, dictionaries, and more.
def my_function():
  return ["apple", "banana", "cherry"]

fruits = my_function() #outcome of my_function (list) is assigned to fruits
print(fruits[0])
print(fruits[1])
print(fruits[2])
print(fruits)

apple
banana
cherry
['apple', 'banana', 'cherry']


In [42]:
def my_function():
  return (10, 20, 30, 40)  #tuple

x, y, z, a = my_function() #values are assigned from the begining index
print("x:", x)
print("a:", a)

x: 10
a: 40


In [ ]:
# Positional-Only Arguments You can specify that a function can have ONLY positional arguments.

# To specify positional-only arguments, add , / after the arguments:
def my_function(name, /):
  print("Hello", name)

my_function("Emil")

Hello Emil


In [ ]:
# Without the , / you are actually allowed to use keyword arguments even if the function expects positional arguments:
def my_function(name):
  print("Hello", name)

my_function(name = "Emil")



Hello Emil


In [ ]:
# Keyword-Only Arguments To specify that a function can have only keyword arguments, add *, before the arguments:
def my_function(*, name):
  print("Hello", name)

my_function(name = "Emil")

Hello Emil


In [ ]:
# Without *,, you are allowed to use positional arguments even if the function expects keyword arguments:
def my_function(name):
  print("Hello", name)

my_function("Emil")

Hello Emil


In [46]:
def my_function(*kids): #variable length arguments or parameters
  print("The youngest child is " + kids[3]) # list of arguments will be taken

my_function("Emil", "Tobias", "Linus", "Tom", "Harry")

The youngest child is Tom


In [47]:
#Accessing individual arguments from *args:
def my_function(*args):
  print("Type:", type(args))
  print("First argument:", args[0])
  print("Second argument:", args[1])
  print(args[3])
  print(args[2])
  print("All arguments:", args)

my_function("Emil", "Tobias", "Linus", "Tom", "Harry")

Type: <class 'tuple'>
First argument: Emil
Second argument: Tobias
Tom
Linus
All arguments: ('Emil', 'Tobias', 'Linus', 'Tom', 'Harry')


In [48]:
# Using *args with Regular Arguments
# You can combine regular parameters with *args.

# Regular parameters must come before *args:
def my_function(greeting, *names): #combination is allowed
  for i in names:
    print(greeting, i)

my_function("Hello", "Emil", "Tobias", "Linus", "Tom", "Harry") #positional argument

Hello Emil
Hello Tobias
Hello Linus
Hello Tom
Hello Harry


In [49]:
def my_function(*numbers):  #summation of multiple numbers #variable length argument
  total = 0
  for num in numbers:
    total += num
  return total

print(my_function(1, 2, 3))
print(my_function(10, 20, 30, 40))
print(my_function(5))
print("This is the usecase of variable length arguments")

6
100
5
This is the usecase of variable length arguments


1. Finding the maximum value from a list of numbers


In [ ]:
#Finding the maximum value from a list of numbers
def my_function(*numbers):
  if len(numbers) == 0:
    return None #basecase
  max_num = numbers[0]
  for num in numbers:
    if num > max_num:
      max_num = num
  return max_num

print(my_function(3, 7, 2, 9, 1))

9


Passing a list as an argument through a function

In [52]:
def process_list(my_list):
  for item in my_list:
    print(item)
fruits = [1, 2, 3,4,56,7,8] #assigning a list
process_list(fruits) #passing a list
print(type(fruits))

1
2
3
4
56
7
8
<class 'list'>


2. Take a list of numbers as an argument of function, then return the sorted list.


In [7]:
def sort_numbers(num_list):
    sorted_list = sorted(num_list)   # built-in sorting function
    return sorted_list

# Example usage
numbers = [5, 2, 9, 1, 3]
print(sort_numbers(numbers))

[1, 2, 3, 5, 9]


3. Take a list of names and surnames through a function, then print the whole names.
Example: ["Medhasree", "Raj", "Joy", "Ken"]
["Ghosh", "Roy", "Thakur", "Das"]

Result: ["Medhasree Ghosh", "Raj Roy", "Joy Thakur", "Ken Das"]

In [8]:
def full_names(first_names, surnames):
    result = []
    for i in range(len(first_names)):
        result.append(first_names[i] + " " + surnames[i])
    return result


# Example usage
names = ["Medhasree", "Raj", "Joy", "Ken"]
surnames = ["Ghosh", "Roy", "Thakur", "Das"]

print(full_names(names, surnames))

['Medhasree Ghosh', 'Raj Roy', 'Joy Thakur', 'Ken Das']


* means any number of positional arguments
** means any number of keyword arguments

In [10]:
def my_function(**kid):  #Using **kwargs to accept any number of keyword arguments:
  print("His last name is " + kid["lname"])

my_function(fname = "Tobias", lname = "Refsnes")

His last name is Refsnes


In [ ]:
def my_function(**myvar): #Accessing values from **kwargs:
  print("Type:", type(myvar))
  print("Name:", myvar["name"])
  print("Age:", myvar["age"])
  print("All data:", myvar)

my_function(name = "Tobias", age = 30, city = "Bergen")


Type: <class 'dict'>
Name: Tobias
Age: 30
All data: {'name': 'Tobias', 'age': 30, 'city': 'Bergen'}


Mix of fixed length and variable lengthened keyword arguments and positional argument

In [ ]:
def my_function(username, **details):
  print("Username:", username)
  print("Additional details:")
  for key, value in details.items():
    print(" ", key + ":", value)

my_function("emil123", age = 25, city = "Oslo", hobby = "coding")

Username: emil123
Additional details:
  age: 25
  city: Oslo
  hobby: coding


A mix of single positional, variable positional and variable keyword arguments

In [ ]:
def my_function(title, *args, **kwargs):
  print("Title:", title)
  print("Positional arguments:", args)
  print("Keyword arguments:", kwargs)

my_function("User Info", "Emil", "Tobias", age = 25, city = "Oslo")

Title: User Info
Positional arguments: ('Emil', 'Tobias')
Keyword arguments: {'age': 25, 'city': 'Oslo'}


In [ ]:
#Using * to unpack a list into arguments
def my_function(a, b, c):
  return a + b + c

numbers = [1, 2, 3]
result = my_function(*numbers) # Same as: my_function(1, 2, 3)
print(result)

6


In [ ]:
# Unpacking Dictionaries with **
# If you have keyword arguments stored in a dictionary, you can use ** to unpack them:
def my_function(fname, lname):
  print("Hello", fname, lname)

person = {"fname": "Emil", "lname": "Refsnes"}
my_function(**person) # Same as: my_function(fname="Emil", lname="Refsnes")

Hello Emil Refsnes


Locality of a variable

In [ ]:
def myfunc():
  x = 300   #A variable created inside a function is available inside that function:
  print(x)
myfunc()
#this x is called a local variable

300


In [ ]:
#The local variable can be accessed from a function within the function
def myfunc():
  x = 300
  def myinnerfunc(): #nested function
    print(x)
  myinnerfunc()

myfunc()

300


In [53]:
#A variable created outside of a function is global and can be used by anyone:
x = 300 #globally defined, outside the scope of any function

def myfunc():
  print(x)

myfunc()
def myfunc2():
  print(x+2)
myfunc2()
print(x)

300
302
300


In [55]:
x = 300 #globally defined x

def myfunc():
  x = 200  #locally defined x
  print(x) #partof the function
  print(x+2)
myfunc() #The function will print the local x, and then the code will print the global x:

print(x)#will acess global x, not a part of myfunc()

200
202
300


In [58]:
#If you use the global keyword, the variable belongs to the global scope:
def myfunc():
  global x #keyword global will make x a global variable
  x = 300
  print(x)
  myfunc()

print(x)

300


In [ ]:
#Also, use the global keyword if you want to make a change to a global variable inside a function.
#To change the value of a global variable inside a function, refer to the variable by using the global keyword:
x = 300

def myfunc():
  global x
  x = 200

myfunc()

print(x)

200


In [ ]:
#If you use the nonlocal keyword, the variable will belong to the outer function:
def myfunc1():
  x = "Jane"
  def myfunc2(): #nested under myfunc1()
    nonlocal x
    x = "hello"
  myfunc2()
  return x

print(myfunc1())


hello


In [59]:
#Understanding the LEGB rule: #B stands for built-in
x = "G stands for global" #globally defined x

def outer():
  x = "E stands for enclosing"
  def inner(): #nested function #definition of inner function
    x = "L stands for local"
    print("Inner:", x)
  inner() #1 #calling inner()
  print("Outer:", x)

outer()#2 #calling the outer function
print("Global:", x)#3
#Python looks for variables in this order:

# L → Local (inside current function)
# E → Enclosing (outer function)
# G → Global (top of file)
# B → Built-in (Python keywords/functions)
# Each function has its own separate x.

# They DO NOT overwrite each other.

Inner: L stands for local
Outer: E stands for enclosing
Global: G stands for global


In [60]:
#A basic decorator that uppercases the return value of the decorated function.
def changecase(func):
  def myinner():
    return func().upper()
  return myinner

@changecase
def myfunction():
  return "medhasree"

print(myfunction())
#By placing @changecase directly above the function definition, the function myfunction is being "decorated" with the changecase function.

#The function changecase is the decorator.

#The function myfunction is the function that gets decorated.



MEDHASREE


In [ ]:
#A decorator can be called multiple times. Just place the decorator above the function you want to decorate.
def changecase(func):
  def myinner():
    return func().upper()
  return myinner

@changecase
def myfunction():
  return "Hello Sally"

@changecase
def otherfunction():
  return "I am speed!"

print(myfunction())
print(otherfunction())

HELLO SALLY
I AM SPEED!


In [ ]:
x = lambda a : a + 10  #Add 10 to argument a, and return the result:
print(x(5)) #here a=5

15


In [ ]:
#Lambda functions can take any number of arguments:
#Multiply argument a with argument b and return the result:
x = lambda a, b : a * b
print(x(5, 6))

30


In [62]:
#Summarize argument a, b, and c and return the result:
x = lambda a, b, c : a * b + c
print(x(10, 6, 2))


62


In [64]:
def myfunc(n):
  return lambda a : a * n  #Use that function definition to make a
  #function that always doubles the number you send in:

mydoubler = myfunc(2) #n =2

print(mydoubler(11)) #a=11
#result = 11*2=22

22


In [65]:
#Or, use the same function definition to make a function that always triples the number you send in:
def myfunc(n):
  return lambda a : a % n

mytripler = myfunc(3)

print(mytripler(11))
#11%3 = 2 remainder operation

2


In [68]:
#Or, use the same function definition to make both functions, in the same program:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)
mytripler = myfunc(3)
another = myfunc(4)

print(mydoubler(9))#a=9, n = 2
print(mytripler(11)) #a=11, n = 3
print(another(10)) #a=10, n =4

18
33
40


In [ ]:
#Lambda with Built-in Functions
#Lambda functions are commonly used with built-in functions like map(), filter(), and sorted().
#Using Lambda with map()
#The map() function applies a function to every item in an iterable:
#Double all numbers in a list:
numbers = [1, 2, 3, 4, 5]
doubled = list(map(lambda x: x * 2, numbers))
print(doubled)

[2, 4, 6, 8, 10]


In [70]:
#Using Lambda with filter()
#The filter() function creates a list of items for which a function returns True:
#Filter out even numbers from a list:
numbers = [1, 2, 3, 4, 5, 6, 7, 8]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(even_numbers)

[2, 4, 6, 8]


In [ ]:
# Using Lambda with sorted()
# The sorted() function can use a lambda as a key for custom sorting:

# Example
# Sort a list of tuples by the second element:
students = [("Emil", 25), ("Tobias", 22), ("Linus", 28)]
sorted_students = sorted(students, key=lambda x: x[1])
print(sorted_students)

[('Tobias', 22), ('Emil', 25), ('Linus', 28)]


In [ ]:
words = ["apple", "pie", "banana", "cherry"]
sorted_words = sorted(words, key=lambda x: len(x))   #Sort strings by length:
print(sorted_words)

['pie', 'apple', 'banana', 'cherry']


Recursion means a function calling itself.

In [ ]:
#A simple recursive function that counts down from 5:

def countdown(n):
  if n <= 0:  #basecase
    print("Done!")
  else:
    print(n)
    #recursive case
    countdown(n - 1) #countdown is calling itself again with another argument

countdown(5) #initial n = 5

5
4
3
2
1
Done!


In [72]:
#Identifying base case and recursive case:
#0! = 1, 1!=1, 2!=2*1=2, 3!=3*2*1=6, 4!=4*3*2*1=24....
#4!=4*3!, 5=5*4!,6!=6*5!,.....
def factorial(n):
  # Base case
  if n == 0 or n == 1:
    return 1
  # Recursive case
  else:
    return n * factorial(n - 1)

print(factorial(4))

24


In [ ]:
#Find the 7th number in the Fibonacci sequence:
#Fibonacci series = a sequence of numbers where each
#number is the sum of the previous two.
#first two will be 0, 1
#example, 0, 1, 1(0+1), 2(1+1), 3, 5, 8, 13....

def fibonacci(n):
  if n <= 1:
    return n #base case
  else:
    return fibonacci(n - 1) + fibonacci(n - 2) #recursive case

print(fibonacci(7))

13


In [ ]:
# Recursion can be used to process lists by handling one element at a time:

# Example
# Calculate the sum of all elements in a list:

def sum_list(numbers):
  if len(numbers) == 0:
    return 0
  else:
    return numbers[0] + sum_list(numbers[1:])

my_list = [1, 2, 3, 4, 5]
print(sum_list(my_list))

15


In [ ]:
#Find the maximum value in a list:

def find_max(numbers):
  if len(numbers) == 1:
    return numbers[0]
  else:
    max_of_rest = find_max(numbers[1:])
    return numbers[0] if numbers[0] > max_of_rest else max_of_rest

my_list = [3, 7, 2, 9, 1]
print(find_max(my_list))

9


In [ ]:
#A simple generator function:
#Generators allow you to iterate over data without storing the entire dataset in memory.

#Instead of using return, generators use the yield keyword.
def my_generator():
  yield 1
  yield 2
  yield 3

for value in my_generator():
  print(value)


1
2
3


In [ ]:
#Generator that yields numbers:
def count_up_to(n):
  count = 1
  while count <= n:
    yield count
    count += 1

for num in count_up_to(5):
  print(num)

1
2
3
4
5


Introduction to Libraries
1. Numpy
2. Pandas
3. Matplotlib

In [73]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
type(arr) #Dimensions in Arrays
# A dimension in arrays is one level of array depth (nested arrays).

# nested array: are arrays that have arrays as their elements.

numpy.ndarray

In [ ]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# Higher Dimensional Arrays
# An array can have any number of dimensions.

# When the array is created, you can define the number of dimensions by using the ndmin argument.

# Example
# Create an array with 5 dimensions and verify that it has 5 dimensions:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)
#In this array the innermost dimension (5th dim) has 4 elements,
#the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector,
#the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [77]:
# Access Array Elements
# Array indexing is the same as accessing an array element.

# You can access an array element by referring to its index number.

# The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

# ExampleGet your own Python Server
# Get the first element from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[3])

4


In [ ]:
# Access 2-D Arrays
# To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

# Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

# Example
# Access the element on the first row, second column:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
#To access elements from 3-D arrays we can use comma separated
#integers representing the dimensions and the index of the element.
#Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [ ]:
#Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
# Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [ ]:
# Slicing 2-D Arrays
# Example
# From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
# Sort the array:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
# Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
# The example above will return a tuple: (array([3, 5, 6],)

# Which means that the value 4 is present at index 3, 5, and 6.
print(x)

(array([3, 5, 6]),)


In [ ]:
# Joining means putting contents of two or more arrays in a single array.

# In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

# We pass a sequence of arrays that we want to join to the concatenate() function,
# along with the axis. If axis is not explicitly passed, it is taken as 0.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
# Splitting is reverse operation of Joining.

# Joining merges multiple arrays into one and Splitting breaks one array into multiple.

# We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# Print the shape of a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
# Reshaping arrays
# Reshaping means changing the shape of an array.

# The shape of an array is the number of elements in each dimension.

# By reshaping we can add or remove dimensions or change number of elements in each dimension.

# Convert the following 1-D array with 12 elements into a 2-D array.

# The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Convert the following 1-D array with 12 elements into a 3-D array.

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

# Can We Reshape Into any Shape?
# Yes, as long as the elements required for reshaping are equal in both shapes.

# We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but
#we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [ ]:
import pandas as pd
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)


    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [ ]:
# A Pandas Series is like a column in a table.

# It is a one-dimensional array holding data of any type.
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64


In [ ]:
# A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.
# Get your own Python Server
# Create a simple Pandas DataFrame:

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45


In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>
